### ISSUE TITLE
Add support for datasets in test pipeline

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#103]
We need to be able to specify a `dataset.csv` in the test scenario. if there is a `paper.pdf` it will be used to seed a `document` which will be sent to the data profiling endpoint along with the newly seeded dataset; if not, no `document_id` will be provided to the test.

In the future, we can add an optional `dataset_readme.md` or something that can be used to seed a data specific document for use in profiling. This is a longer term TODO

**Comment by Sorrento110** [comment]
Closed in #123
