### ISSUE TITLE
User should be able to specify specific scenarios to run in the reporting pipeline

### ISSUE THREAD

**Issue by Sorrento110** [DARPA-ASKEM/knowledge-middleware#111]
Right now all scenarios will be run every time the reporting pipeline is invoked. Some configuration mechanism should be implemented to select the scenarios to be run.

**Comment by brandomr** [comment]
Anything after `tests` in the `docker compose` command will be appended to the `Dockerfile`'s `CMD` so we need to just update `report.py` to accept arguments
