### ISSUE TITLE
Add dynamics support into the test pipeline

### ISSUE THREAD

**Issue by Sorrento110** [DARPA-ASKEM/knowledge-middleware#119]
Adding support for code dynamics requires either: 

1. specifying some file like `dynamics.json` to be included in the scenario
2.  the scenario code only contains the dynamics of the code to be tested. 

In the case of solution 1, the dynamics need to be seeded into the code object when the seeding process happens. Then when the code_to_amr pipe is run we will use the `dynamics_only` functionality.

**Comment by brandomr** [comment]
To make things simple, we will allow for people to specify a `dynamics.*` file at the top of a scenario which would contain all the code dynamics. If dynamics exist in a repo across multiple files it will be up to the creator of the scenario to concatenate those dynamics into a single file.

This will be _in lieu of a `code.zip`_; a scenario can have only 1 or the other!

If `dyanmics.*` is provided it is assumed that _all lines_ in the file contain the dynamics; the object created in TDS will have a single dynamics block containing lines `1-n` of the file.
