### ISSUE TITLE
Update variable extraction scoring in report

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#160]
TA1 has a new `variable extraction` scoring capability--this issue is to update the integration with that so the latest scores are shown on the dashboard.

**Comment by brandomr** [comment]
@enoriega I think you showed something around this last week--could you point me to the endpoint you were using? Did you just use the MIT `evaluation/eval_var_extraction` endopint?

**Comment by enoriega** [comment]
For variable extraction:
- https://api.askem.lum.ai/docs#/text%20reading/quantitative_eval_text_reading_eval_get
- https://api.askem.lum.ai/docs#/text%20reading/quantitative_eval_text_reading_eval_post (This receives files as part of the request body)

For AMR alignment:
- https://api.askem.lum.ai/docs#/metal/quantitative_eval_metal_eval_post

**Comment by brandomr** [comment]
@enoriega for which scenarios/papers do you have ground truth files for the variable extraction? Where can I find those ground truth files?

**Comment by brandomr** [comment]
@enoriega just wanted to check on the GT files again

**Comment by brandomr** [comment]
From @enoriega:

> To make it more reliable now in addition to the ground truth and extraction files, now we also use the cosmos json file. This is more effective to track back the text span of the extractions to the source (hence the need for carrying fwd the cosmos json file), than trying to reconstruct something to test against the annotations. I put together a unit test that works as an example of how to all it https://github.com/ml4ai/skema/blob/main/skema/rest/tests/test_integrated_text_reading_proxy.py#L92C4-L119

Since we store the `extractions` on the `document` as `document.metadata` after Cosmos processing.
