### ISSUE TITLE
PDF extraction-to-model linking in knowledge-middleware

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/knowledge-middleware#22]
@brandomr please add a description and estimate the amount of work

**Comment by brandomr** [comment]
The `/link_amr` endpoint is not complete and should follow the MORAE logic outlined here: https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/main/morae-demo/MORAE_demo.ipynb

probably a day or 2 to knock out

**Comment by brandomr** [comment]
@enoriega @Free-Quarks i’m trying https://api.askem.lum.ai/docs#/metal/link_amr_metal_link_amr_post but getting a 500 error. Is that endpoint working yet? Is there an example AMR/extraction file I should use?

I’m currently trying with the [basic examples here](https://github.com/DARPA-ASKEM/knowledge-middleware/tree/main/tests/scenarios/basic):

- [AMR](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/amr.json)
- [Extractions](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/extractions.json)

**Comment by enoriega** [comment]
@brandomr This is a simple bug. I will open a ticket and fix it. Thanks for finding out!

**Comment by enoriega** [comment]
@brandomr There is a fix for this in https://github.com/ml4ai/skema/pull/443
It will trickle down into the docker image once CI finishes
