### ISSUE TITLE
Optionally update existing model with `equations to AMR` 

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#31]
Per @YohannParis there is a need to use `/equations_to_amr` to re-run equations for an existing model. To support this, the endpoint should optionally take `model_id`. If provided, the resulting AMR would update the model in place instead of creating a new one.

**Comment by YohannParis** [comment]
It's not entirely accurate, but still right.
On the HMI we create an empty model (with an id, name, and description) before letting the user open it and entering equations, therefore we need to update this "empty" but already existing model.

**Comment by brandomr** [comment]
@YohannParis got it--so there won't be existing metadata that needs to be brought over. It's just updating the empty shell with something real

**Comment by YohannParis** [comment]
> @YohannParis got it--so there won't be existing metadata that needs to be brought over. It's just updating the empty shell with something real

You are right! Just an `id, name, description` will be present.
