### ISSUE TITLE
Replace `/pdf_to_text` with Cosmos call instead of SKEMA call

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#34]
## Current state

We currently use SKEMA's `/text-reading/cosmos_to_json` endpoint to get text from the PDF. We drop the remaining extractions from Cosmos after joining the text together and storing it to the `artifact` metadata.

## Proposed future state

We should directly call Cosmos for raw PDF processing per [UWisc's notebook](https://github.com/UW-COSMOS/Cosmos/blob/master/notebooks/cosmos-service/cosmos_service.ipynb). We should store the results directly on the `document` that is saved to TDS.

This assumes that the `artifact` usage in KM will be replaced by `documents` in TDS [as per #35](https://github.com/DARPA-ASKEM/knowledge-middleware/issues/35)

## Considerations

Cosmos is interesting in that once a PDF is processed there are multiple endpoints available to the client to fetch results. We will need to store a lot of files (images and tables) to the TDS `documents` as well as the PDF. Should we consider how to differentiate between these? I worry the frontend may not know which file is which. 

Additionally, we might want to consider renaming this endpoint to something more generic like `/process_document` since we will likely need to handle other (non-PDF) formats like `md`, `doc`, `txt`, etc.

**Comment by iross** [comment]
Feel free to ping @mwestphall or myself for any questions or needs.

**Comment by brandomr** [comment]
Thanks @iross! 

@mattprintz @YohannParis per @mwestphall cosmos is only accepting PDFs right now so we probably want some kind of handler on the HMI server end that detects the file type and if it's plain text (e.g. `.md` or `.txt`) just takes the text and stores it to `document.text` in TDS without sending to this endpoint for now

**Comment by YohannParis** [comment]
@brandomr sure, we can make sure to only send PDF to that endpoint. Then we should make a `.pdf` verification on KM before making the call to COSMOS for extra safety.

As for saving the extra information returned by COSMOS, like we talked about it, lets just save them in S3, and we will display them on the HMI like we do with xDD extractions. Then we can offer to the user to do something about when they decide to process one.

**Comment by orm011** [comment]
I think its likely MIT APIs like extraction will in the near future want to get the full package returned by cosmos as one of the arguments, to take full advantage of the work of Wisc,  so keeping enough information to do that is helpful.
