### ISSUE TITLE
Add ground truth for COSMOS region annotation tests

### ISSUE THREAD

**Issue by mwestphall** [DARPA-ASKEM/knowledge-middleware#67]
Ian has manually annotated the [SIDARTHE paper](https://www.nature.com/articles/s41591-020-0883-7.pdf) and a markdown document for the [BUCKY model](https://github.com/UW-COSMOS/Cosmos/blob/master/cosmos_service/test/resources/pdfs/bucky.pdf) with expected bounding boxes and region classifications. 

The annotations are currently stored as a series of per-pdf, per-page XML documents in the XDD COSMOS repo:
https://github.com/UW-COSMOS/Cosmos/tree/master/cosmos_service/test/resources/annotated/sidarthe

Tests against these manual annotations for 3 region classifications (equations, tables, and figures) are implemented in the XDD COSMOS repo:
https://github.com/UW-COSMOS/Cosmos/blob/master/cosmos_service/test/src/annotations/test_sidarthe.py

These tests check for at least 90% agreement between COSMOS and the manual annotations on each page of each given document, and fail if any page is at under 90% agreement. This may or may not be a suitable measurement for the knowledge middleware dashboard. 

The `test_pdf_to_cosmos` test should be updated to:
- Fetch the manual region annotations for the document being processed
- Compare the bounding boxes generated by COSMOS to the manually annotated documents
- Determine the degree to which COSMOS output agrees with the manual annotations based on some metric
- Store results so they can be used in the integration dashboard

**Comment by brandomr** [comment]
@mwestphall this sounds pretty straightforward to me. Is there similar code to test the Bucky results as well? If so, it would be nice if `test_sidarthe.py` could be generecized into something like `evaluate_cosmos_extractions.py` which takes in the cosmos extractions + ground truth file and produces the score.

That said, we could just start with SIDARTHE.

**Comment by brandomr** [comment]
@mwestphall i think to align with how we're handling other quality checks it would be nice to have the ground truth files in this repo. 

@Sorrento110 is starting to work on this now so you could coordinate with him.

**Comment by brandomr** [comment]
@iross @mwestphall related to my above comment--I think MIT is aiming to provide precision and recall; it looks like SKEMA is providing [precision](https://api.askem.lum.ai/docs#/text%20reading/quantitative_eval_text_reading_eval_get) + some other metrics. I'm guessing that it won't always be possible to provide precision and recall but it would be good to get a description of what your metric is (in general terms) so that we can provide that context on the integration dashboard.

> I think it's OK for different teams to use different quality measures as long as we are transparent about how they are derived.

**Comment by mwestphall** [comment]
@brandomr we are currently capturing two metrics in the tests:
- The count of manually annotated regions for each component type on each page, compared to the count identified by COSMOS
- The overlapping area between manually annotated bounding boxes and COSMOS bounding boxes for each component type on each page, as a fraction of the manually annotated area

We currently just pass/fail the tests based on complete agreement between cosmos and the manual annotations (so the majority of tests fail), but we report the actual discrepancies in the stdout of the test. eg:
```

self = <src.annotations.test_sidarthe.TestSidartheAnnotations object at 0x7f91906439a0>

    def test_compare_figure_counts(self):
>       self.check_count_per_page("Figure")

src/annotations/test_sidarthe.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <src.annotations.test_sidarthe.TestSidartheAnnotations object at 0x7f91906439a0>, label_class = 'Figure'

    def check_count_per_page(self, label_class):
        fc = self.compare_pages_for_label(label_class)
        failures = fc.get_failures_per_page(
            f"{label_class} count", fc.expected_counts, fc.cosmos_counts, equals_comparator)
>       assert failures.ok(), failures.error_message()
E       AssertionError: Incorrect Figure count on 11 page(s)
E       page 9: expected=0 actual=1
E       page 12: expected=8 actual=7
E       page 14: expected=8 actual=5
E       page 17: expected=8 actual=3
E       page 19: expected=8 actual=3
E       page 21: expected=8 actual=3
E       page 23: expected=8 actual=3
E       page 25: expected=8 actual=3
E       page 27: expected=8 actual=7
E       page 29: expected=1 actual=5
E       page 32: expected=0 actual=1

src/annotations/annotations_base.py:158: AssertionError
______________________________________________________________________ TestSidartheAnnotations.test_compare_overlapping_figure_areas ______________________________________________________________________

self = <src.annotations.test_sidarthe.TestSidartheAnnotations object at 0x7f91906435e0>

    def test_compare_overlapping_figure_areas(self):
>       self.check_overlap_per_page("Figure")

src/annotations/test_sidarthe.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <src.annotations.test_sidarthe.TestSidartheAnnotations object at 0x7f91906435e0>, label_class = 'Figure'

    def check_overlap_per_page(self, label_class):
        fc = self.compare_pages_for_label(label_class)
        failures = fc.get_failures_per_page(
            f"{label_class} overlap percentage",
            [AREA_BOUNDS for _ in fc.expected_counts],
            fc.overlap_percents,
            in_bounds_comparator)
>       assert failures.ok(), failures.error_message()
E       AssertionError: Incorrect Figure overlap percentage on 5 page(s)
E       page 9: expected=(0.9, 1.1) actual=inf
E       page 14: expected=(0.9, 1.1) actual=1.4810223511694587
E       page 27: expected=(0.9, 1.1) actual=1.1117274215028783
E       page 29: expected=(0.9, 1.1) actual=0.8874352117887453
E       page 32: expected=(0.9, 1.1) actual=inf

src/annotations/annotations_base.py:167: AssertionError
```

**Comment by Sorrento110** [comment]
New Cosmos evaluation endpoint: https://xdd.wisc.edu/cosmos_service/docs#/default/evaluate_results_cosmos_service_healthcheck_evaluate__job_id__post

Example of new ground truth format to feed to the evaluation endpoint: https://github.com/UW-COSMOS/Cosmos/blob/master/notebooks/cosmos-service/sidarthe.pdf.json
