### ISSUE TITLE
Issues with `make up`

### ISSUE THREAD

**Issue by mwestphall** [DARPA-ASKEM/knowledge-middleware#70]
Stepping through the README for local test setup works mostly as expected, but several issues came up with the `make up` command. I ended up skipping it and was still able to run the tests, so it's not critical to get it right.

- It might be worth it to mention that poetry can be installed via `pip install poetry`
- Depending on how you clone the repo, you will also need to run `git submodule init` and `git submodule update` to clone the `askem-ta1-dockervm` submodule. It might be good to note this in the README
- `make up` appears to try to run the command `docker compose up ...` instead of `docker-compose up ...`, which, at least on Ubuntu, does not work
- The base `docker-compose.yaml` file appears to reference a service inside of `askem-ta1-dockervm` that doesn't exist: `skema-unified`

**Comment by mattprintz** [comment]
Great points.

On item # 3, `docker compose` vs `docker-compose`, the former is how the newer version of docker do the command and the latter is the older version.
I believe that Ubuntu 20 by default uses the older version while Ubuntu 22 and forward will all install a version of docker that expects `docker compose`.
You can upgrade your local version of docker by following the instructions here, if you so desire: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

**Comment by mattprintz** [comment]
The readme and make file have been updated and should be a smoother process now. Thanks.
