### ISSUE TITLE
Update quality report to accept JSON

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#80]
We should directly write (do not parse) any quality information received from TA1. This should show up as the raw JSON inside the dashboard. E.g. for model profile:

```
 {"accuracy":"0.7"}
```

In this way, we can allow the TA1 teams maximum flexibility and the opportunity to pass in a live description of how accuracy is measured.

**Comment by fivegrant** [comment]
i think this is solved with the test refactor
