### ISSUE TITLE
`/pdf_extractions` malformed (?)

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#82]
Right now, it seems like we're storing extractions on a `document` like:

```
 ],
  "metadata": {
    "attributes": [
      {
        "type": "anchored_entity",
        "amr_element_id": null,
        "payload": {
          "id": {
            "id": "R:-765462369"
          },
```

but this is causing AMR linking to 🤮 . 

Notice how in our example [`extractions.json`](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/extractions.json#L1) it looks like:

```
{
  "outputs": [
    {
      "data": {
        "attributes": [
          {
```

In other words--it seems like we need `metadata.outputs.data.attributes` not just `metadata.attributes`. I guess we should *not* be parsing the extractions like [we do here](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/worker/operations.py#L363-L381) but @blanchco @YohannParis if we _don't_ parse them it will require some change to how the HMI handles parsing them.

## Proposal

I propose we store the extractions into `metadata` in the way they are expected downstream by SKEMA for consistency and update how the HMI handles them accordingly. We'll need to confirm that changes to this won't break the model profiling/card from MIT as well though.

**Comment by enoriega** [comment]
Oh oh. @brandomr The output of `integrated_pdf_extractions` has an envelope that contains the output + any error messages. I think that is the source of this issue. Can you post a sample file that is crashing the `link_amr` endpoint?

**Comment by brandomr** [comment]
@enoriega it's basically just any extractions that don't have the `output.data` wrapper around `attributes`. If that's expected that's totally fine IMO we should store that information.
