### ISSUE TITLE
`equations_to_amr` rename created model configuration to 'Default config'

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/knowledge-middleware#96]
After some discussion on this [ticket](https://github.com/DARPA-ASKEM/terarium/issues/1731).  We want the _model configuration_ to be created with the `name` and `description` "Default config" rather than the model name when calling the `equations_to_amr` endpoint.

**Comment by brandomr** [comment]
No problem, I just need to update that [here](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/worker/utils.py#L79)
