### ISSUE TITLE
Add support for images to equations (LaTex)

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/knowledge-middleware#97]
This issue is to send an image of equations (a `document.asset` extracted by Cosmos) to SKEMA and get LaTex in return.

@enoriega is there an endpoint for this that we should use? We are relying on LaTeX in the front-end (no MathML right @mwdchang?) so can either get MathML back from you and convert to LaTeX ourselves or better if you can on your side to ensure correctness.

**Comment by enoriega** [comment]
Cc @ualiangzhang for this

**Comment by brandomr** [comment]
@ualiangzhang I see. So the desired user flow for TA4 is:

1. paper is extracted by cosmos
2. cosmos returns various equation images
3. user selects an image of equations and sends to SKEMA
4. SKEMA returns LaTeX
5. User edits the LaTeX and makes sure it's correct
6. User sends LaTeX to SKEMA for conversion to AMR

Since the user space will be LaTeX oriented--is it possible for you to add a converter to your system? If not, we'll do it on our end.

**Comment by ualiangzhang** [comment]
@brandomr Got it. I will discuss your request with the team and get back to you.

**Comment by brandomr** [comment]
@ualiangzhang we'll just handle the conversion from PMML to LaTeX on our side for now

**Comment by ualiangzhang** [comment]
@brandomr Please feel free to let me know if you need any help from our side. Thanks!

**Comment by brandomr** [comment]
@YohannParis for this issue I'm thinking that once we get the equations back we'd store them back to the `document` as metadata on the image asset that was shipped. That keeps everything all together. What do you think?

**Comment by brandomr** [comment]
Based on a discussion on Friday, the calls for this will be initially handled by the HMI. The reasons for this are:

1. Equation extraction from images is somewhat lossy--users will frequently need to make corrections--and storing the raw extracted PMML/LaTeX isn't particularly useful
2. We assume that equations are highly mutable--users will want to edit them as though they are working on a whiteboard
3. Equations can be perfectly represented by an AMR, so storing them as AMRs is preferred to storing the raw equations

The last point is a _significant_ outstanding question mark to address with TA2 on Wednesday since it might be a faulty assumption.

The alternative here is that image to equations are managed via KM and equations themselves are stored as new types of objects (e.g. `equations`) within TDS. These `equations` will have provenance relationships to both `documents` they came from as well as `models` derived from them. We'd also need some kind of edit log for `equations` since it's unreasonable to think that `equations from documents` will 1:1 match the `equations used to model` by the user.

**Comment by YohannParis** [comment]
@Free-Quarks will make an update to SKEMA for that purpose.
